spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock?useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 243211
mybatis:
  configuration:
    map-underscore-to-camel-case: true